src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
    
    #[Assert\GreaterThan("today -1 day", message : "Validation impossible , La date d'Arrivée ne peut pas être anterieure a aujourd'hui")]
    #[ORM\Column(type: 'datetime')]
    private $checkIn;
  
    #[Assert\Expression("this.getCheckIn() < this.getCheckOut()", message : "Validation impossible , La date de Départ doit être ulterieure à la date d'Arrivée")]
    #[ORM\Column(type: 'datetime')]
    private $checkOut;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: Suite::class, inversedBy: 'reservations')]
    private $Suite;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'reservations')]
    private $User;

    public function __construct()
    {       
        $this->createdAt  = new \DateTime;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCheckIn(): ?\DateTimeInterface
    {
        return $this->checkIn;
    }

    public function setCheckIn(\DateTimeInterface $checkIn): self
    {
        $this->checkIn = $checkIn;

        return $this;
    }

    public function getCheckOut(): ?\DateTimeInterface
    {
        return $this->checkOut;
    }

    public function setCheckOut(\DateTimeInterface $checkOut): self
    {
        $this->checkOut = $checkOut;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt ;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSuite(): ?Suite
    {
        return $this->Suite;
    }

    public function setSuite(?Suite $Suite): self
    {
        $this->Suite = $Suite;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function __toString()
    {        
        return $this->Suite ;              
    }            

    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 50)]
    private $lastName;

    #[ORM\Column(type: 'string', length: 50)]
    private $firstName;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: Reservation::class)]
    private $reservations;

    #[ORM\ManyToOne(targetEntity: Company::class, inversedBy: 'users')]
    private $Company;

    #[ORM\ManyToOne(targetEntity: Hotel::class, inversedBy: 'users')]
    private $Hotel;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->Company;
    }

    public function setCompany(?Company $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getHotel(): ?Hotel
    {
        return $this->Hotel;
    }

    public function setHotel(?Hotel $Hotel): self
    {
        $this->Hotel = $Hotel;

        return $this;
    }

    public function __toString()
    {
        return $this->lastName ;
    }   
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;

#[Route('/member/booking')]
class BookingController extends AbstractController
{
    #[Route('/', name: 'booking_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('booking/index.html.twig', [
            'reservations' => $reservationRepository->userBooking($this->getUser()),
        ]);
    }    

    #[Route('/new', name: 'booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {      
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {        
            $user = $this->getUser();
            $reservation->setUser($user);           
            $reservationRepository->add($reservation);
            $this->addFlash('success', 'Votre réservation a été effectuée . Merci');       
            return $this->redirectToRoute('booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }   

    #[Route('/{id}', name: 'booking_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('booking/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->add($reservation);
            return $this->redirectToRoute('booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'booking_delete', methods: ['GET','POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $actualDate = new DateTime();
        $date = $reservation->getCheckIn()->modify('- 2 day');
        if ($date < $actualDate) {
            $this->addFlash('info', 'Suppression impossible , la date est trop proche ou passée ! ');
            return $this->redirectToRoute('booking_index');
        }
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation);
        }

        $this->addFlash('delete', 'Votre réservation a été supprimée avec succés !');
        return $this->redirectToRoute('booking_index', [], Response::HTTP_SEE_OTHER);
    }
    
}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('booking_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn btn-danger my-3">Supprimer</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form, { attr: {'id': 'form_valid' } }) }}
    {{ form_widget(form) }}

    <div id="days" class="pb-4"> 0 Nuitée</div>
    
    <button id="bookingButton" type="submit" class="btn btn-success mb-4">Valider</button>

{{ form_end(form) }}
            	
{% block javascripts %}
{{ encore_entry_script_tags('booking') }}
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Réservations
{% endblock %}

{% block body %}

	<div class="row text-center">			
		<div class=" py-5 col col-sm-12 col-12 space2">				

			{% for message in app.flashes('success') %}
    			<div class="text-center h3 text-success pb-4 flash-success">
        			{{ message }}
				</div>
			{% endfor %}		

			{% for message in app.flashes('info') %}
    			<div class="text-center h4 text-warning pb-4 flash-info">
        			{{ message }}
				</div>
			{% endfor %}  

			{% for message in app.flashes('delete') %}
    			<div class="text-center h3 text-primary pb-4 flash-delete">
        			{{ message }}
				</div>
			{% endfor %}  		  		

			<table class="table text_color color2">
				<thead>
					<tr>						
						<th>Hotel</th>
						<th>Suite</th>
						<th>Date d'Arrivée</th>
						<th>Date de Départ</th>
						<th> </th>
					</tr>
				</thead>
				<tbody>
					{% for reservation in reservations %}
						<tr>							
							<td>{{ reservation.suite.hotel }} - {{ reservation.suite.hotel.city }}</td>
							<td>{{ reservation.suite }}</td>
							<td>{{ reservation.checkIn ? reservation.checkIn|date('d-m-Y') : '' }}</td>
							<td>{{ reservation.checkOut ? reservation.checkOut|date('d-m-Y') : '' }}</td>
							<td>
								<a href="{{ path('booking_show', {'id': reservation.id}) }}" class="btn btn-sm btn-primary" role="button">Selectionner</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="5">Aucun enregistrement</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<a href="{{ path('booking_new') }}" class="btn btn-primary mt-3" role="button">Faire une nouvelle réservation</a>
		</div>					
	</div>
		
{% endblock %}

{% block javascripts %}
{{ encore_entry_script_tags('booking') }}
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Faire une Reservation{% endblock %}


{% block body %}
	<div class="container-fluid text-center">
		<div class="row">
			<div class=" col"></div>
			<div class="col col-lg-4 col-md-5 col-sm-8 col-12 color2 py-5">		

			

				<div id="bookingModal" class="modal fade" tabindex="-1">
					<div class="modal-dialog">
						<div class="modal-content color2">								
							<div class="modal-body text_color py-5">
								<h3>Reservation en cours</h3>									
								<button type="button" class="btn btn-secondary my-3" data-bs-dismiss="modal">Quitter</button>									
							</div>
						</div>
					</div>
           		</div>

				{{ include('booking/_form.html.twig') }}		
										
				<a  href= "{{ path('booking_index') }}" class="btn btn-primary my-3"  role="button">Retour</a> 			
				
			</div>
			<div class="col"></div>
		</div>
	</div class="btn btn-info>
{% endblock %}

{% block stylesheet %}
{{ encore_entry_link_tags('datepicker') }}
{% endblock %}

{% block javascripts %}
{{ encore_entry_script_tags('datepicker') }}
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre Réservation{% endblock %}

{% block body %}
	<div class="container-fluid text-center">
		<div class="row py-5">
			<div class="col"></div>
			<div class="col col-lg-4 col-md-6 col-sm-9 col-12">

				<table class="table text_color">
					<tbody>
						<tr>
							<th>Hotel</th>
							<td>{{ reservation.suite.hotel }} - {{ reservation.suite.hotel.city }}</td>
						</tr>
						<tr>
							<th>Suite</th>
							<td>{{  reservation.suite.title}}</td>
						</tr>
						<tr>
							<th>Date d'Arrivée</th>
							<td>{{ reservation.checkIn ? reservation.checkIn|date('d-m-Y') : '' }}</td>
						</tr>
						<tr>
							<th>Date de Depart</th>
							<td>{{ reservation.checkOut ? reservation.checkOut|date('d-m-Y') : '' }}</td>
						</tr>
						<tr>
							<th>Reservé le</th>
							<td>{{ reservation.createdAt ? reservation.createdAt|date('d-m-Y') : '' }}</td>
						</tr>
					</tbody>
				</table>

				
				<a href= "{{ path('booking_index') }}" class="btn btn-info my-3"  role="button">Retour</a>      			

				{{ include('booking/_delete_form.html.twig') }}
				<p> La suppression d'une réservation est possible jusqu'à 3 jours à l'avance </p>

			</div>
			<div class="col"></div>
		</div>
	</div>
	
{% endblock %}